### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by Mzeey** [mzeey-tutorials/NepaApp#24]
### Description
As an unregistered user, I want to create an account so that I can log in to the Nepa app.

### Acceptance Criteria
- [ ] I can access the "Sign Up" page.
- [ ] I can enter my first name, last name, email address, and password.
- [ ] Password meets the security requirements.
- [ ] I receive a confirmation email after signing up.
- [ ] The confirmation email contains a verification link.
- [ ] Clicking the verification link activates my account.
- [ ] Upon successful activation, I can log in with my credentials.

### Tasks
- [ ] #51
- [ ] #65 
- [ ] #73 
- [ ] #74 
- [ ] #75 
- [ ] #76 
- [ ] #77 
- [ ] #78 
- [ ] #79 
- [ ] #80 
- [ ] #81
