### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by Mzeey** [mzeey-tutorials/NepaApp#31]
### Description
As a customer user, I want to recover my account so that I can have access to it after I have lost my password.

### Acceptance Criteria
- [ ] I can access the "Forgot Password" option from the login page.
- [ ] The "Forgot Password" option guides me through the process of account recovery.
- [ ] I can provide information to verify my identity, such as email address or other account-related details.
- [ ] After verification, I receive an email with instructions and a link to reset my password.
- [ ] Clicking the link allows me to set a new password for my account.

### Tasks
- [ ] #53
- [ ] Implement the Account Recovery Process pages.
- [ ] Create a step-by-step process for account recovery.
- [ ] Develop logic for account recovery process.
- [ ] #54
- [ ] #55
- [ ] Integrate the account recovery process with the app's navigation.
