### ISSUE TITLE
Implement Login Mockup (Integration with frontend)

### ISSUE THREAD

**Issue by Mzeey** [mzeey-tutorials/NepaApp#82]
### Description
implement the UI mockup for the login page, ensuring it integrates seamlessly with the frontend. The login page should lead to the dashboard on successful login, and if the user is not verified, it should redirect to the Email Verification Required page. Render appropriate messages and cues to guide the user through the process.

### Acceptance Criteria
- [ ] Leads to the dashboard page on login success.
- [ ] If the user is not verified, leads to the Email Verification Required page.
- [ ] Ensure to render appropriate messages and cues to the user if needed.

### User Story
- #25 

### Task Dependencies
- [ ] #64
